# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e16ee13202219299394c58d57f9eaf8e8cc69afb920e7d8fc335f0abb511a071e664c1d9d8ac77146cf8d46ffcfbdce671ed3459c9e6fb0733680502acf983b6

test:
  secret_key_base: f86bf8388298c6fe61ada76445f3d9a1a657d678b36fe3004af693334ddd4d3392659c2ca41164647b20e935a9d59c179f982ba48746d912fdd3bef9df2c8461

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
